<?xml version="1.0" encoding="UTF-8" ?> 
<?xml-stylesheet type="text/css" href="1.css"?>
<!DOCTYPE contact-info [ 
<!ELEMENT contact-info (name, zag, info)> 
<!ELEMENT name (#PCDATA)> 
<!ELEMENT header (#PCDATA)> 
<!ELEMENT info (#PCDATA)> 
<!ENTITY X "!">
<!ENTITY p "-">
<!ENTITY d ">">
<!ENTITY n "<">
]> 


<contact-info>
  <name>XML</name>
  <header>&lt;Логическая структура&gt;</header>
  <info>Все составляющие части документа обобщаются в пролог и корневой элемент. Корневой элемент — обязательная часть документа, составляющая всю его суть (пролог, вообще говоря, может отсутствовать). Корневой элемент может включать (а может не включать) вложенные в него элементы, символьные данные и комментарии. Вложенные в корневой элемент элементы, в свою очередь, могут включать вложенные в них элементы, символьные данные и комментарии, и так далее.</info>
  <header>&lt;Объявление XML&gt; </header>
  <info>Объявление XML указывает версию языка, на которой написан документ. Поскольку интерпретация содержимого документа зависит от версии языка, то Спецификация предписывает начинать документ с объявления XML. В первой (1.0) версии языка использование объявления не было обязательным, в последующих версиях оно обязательно. Таким образом, версия языка определяется из объявления, и если объявление отсутствует, то принимается версия 1.0.</info>
</contact-info>